spring:
  application:
    name: inventory-service

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

custom-circuit-breaker:
  failure-threshold: 5
  reset-timeout-seconds: 30